# Generated by Django 5.1.3 on 2024-11-11 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
